### ISSUE TITLE
VAC Ban 02.03.2018

### ISSUE THREAD

**Issue by 0xE232FE** [mircea32000/GAYWARE#1]
I got VAC Banned even with Junked version of this cheat!

Used private undetected injector manual mapping!

**Comment by akrw** [comment]
lmao get rekt bitch

**Comment by 0xE232FE** [comment]
I know why I am banned. It was manual map injector. I am smarter now coding my own Driver Injector with Code Base of https://github.com/z175/kdmapper
KDMapper is best source for it. I use Simple SDK and my own Cheat development driven far to super legit cheating on Leagues like ESL and FaceIT. Never banned since 2018 anymore!
